---

- name: Ensure dependencies are installed
  package:
    name:
      - tar
      - unzip
      - gzip
    state: present

- name: Ensure install dir exists
  become: yes
  file:
    state: directory
    owner: root
    group: '0'
    mode: 'u=rwx,go=rx'
    dest: '{{ maven_install_root }}'

- name: Downloading maven version
  get_url:
    url: '{{ maven_download_url }}/{{ maven_file_name }}'
    dest: '{{ maven_install_root }}/{{ maven_file_name }}'
  
- name: Unpack maven binaries
  unarchive:
    src: '{{ maven_install_root }}/{{ maven_file_name }}'
    dest: '{{ maven_install_root }}'
    creates: '{{ maven_install_root }}/apache-maven-{{ maven_version }}'
    copy: no

- name: Create mvn symlink
  file:
    state: link
    force: yes
    src: '{{ maven_install_root }}/apache-maven-{{ maven_version }}/bin/mvn'
    dest: '/usr/local/bin/mvn'
    owner: root
    group: '0'
    mode: 'u=rwx,go=rx'